name: pages
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Bun
      uses: oven-sh/setup-bun@v2

    - name: Publish Package
      run: bun publish --access public

    - name: Configure
      uses: actions/configure-pages@v5

    - name: Upload
      uses: actions/upload-pages-artifact@v4
      with:
        path: 'dist'

    - name: Deploy
      uses: actions/deploy-pages@v4
      id: deployment
