name: publish
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Bun
      uses: oven-sh/setup-bun@v2

    - name: Publish Package
      run: bun publish
